environment: production

theme: jekyll-theme-primer
url: "https://finance.adriant.io"

author:
  name: Adrian Teng-Amnuay
  email: pumpadrian@gmail.com

title: personal finance
description: a blog on financial freedom, early retirement, trading and investing ideas for millenials and zoomers

google_analytics: UA-117405938-6
google_adsense: 
disqus_forum_name: adriant-io

plugins:
- jekyll-sitemap
- jekyll-paginate
- jekyll-feed
- jekyll-redirect-from

feed:
  path: atom.xml

exclude: [vendor, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock, script]

excerpt_separator: <!--more-->

permalink: pretty

paginate: 5
paginate_path: /page:num/

defaults:
- scope:
    path: ""
    type: "posts"
  values:
    comments: true

images: /assets/img/
