environment: production

theme: jekyll-theme-primer
url: "https://finance.adriant.io"

author:
  name: Adrian Teng-Amnuay
  email: pumpadrian@gmail.com

title: finance.adriant.io
description: a finance blog for millenials and zoomers

google_analytics: UA-117405938-3
google_adsense: ca-pub-3521905629903035
disqus_forum_name: adriant-io

plugins:
- jekyll-sitemap
- jekyll-paginate
- jekyll-feed
- jekyll-redirect-from

feed:
  path: atom.xml

exclude: [CNAME, README.md, .gitignore, Gemfile, Gemfile.lock, script]

excerpt_separator: <!--more-->

permalink: pretty

paginate: 5
paginate_path: /page:num/

defaults:
- scope:
    path: ""
    type: "posts"
  values:
    comments: true

images: /assets/img/
